spring:
  datasource:
    url: {server-url}
    username: {username}
    password: {password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: {REDIS_HOST}
      port: {REDIS_PORT}
      password: {REDIS_PASSWORD}
server:
  port: {server-port}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}   #172800000    # 48시간
  refreshExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION} #604800000   # 7일