name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "."
          target: "~/app"

      - name: Run remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          timeout: 300s
          script: |
            sudo apt update
            sudo apt install openjdk-17-jdk -y

            cd ~/app
            chmod +x gradlew
            ./gradlew build -x test

            JAR_FILE=$(ls build/libs/*.jar)
            if [ -f "$JAR_FILE" ]; then
              java -jar $JAR_FILE
            else
              echo "No JAR file found, build failed."
              exit 1
            fi
      
